name: Deploy Website

on:
  push:
    branches:
      - main  # или master — ваша основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # папка с вашим сайтом

